### ISSUE TITLE
Similar research

### ISSUE THREAD

**Issue by szepeviktor** [stevegrunwell/platform-plugin#1]
Hello Steve!
There is no guidance from WordPress how to write a plugin. I mean they are very liberal.
This is my research result on what to put in the main file.
https://github.com/szepeviktor/small-project/blob/master/MAIN-FILE-PARTS.md
Striving to leave legacy technologies behind.
Some PHP code is included.
What do you think?

**Comment by stevegrunwell** [comment]
Overall, I think everything you have makes sense. It's certainly opinionated and there are items in there I don't totally agree with (for instance, I'm totally fine with namespaced constants and don't think those need to be defined within a container, and I don't care for the `if (! defined('ABSPATH')) exit;` pattern), but the general idea should be "load whatever you need to bootstrap the plugin."

**Comment by szepeviktor** [comment]
> but the general idea should be "load whatever you need to bootstrap the plugin."

You know, I like strict rules. So I make them :)
